### ISSUE TITLE
Add Xcode version specification for the challenges 

### ISSUE THREAD

**Issue by kostiakoval** [Kametrixom/The-Swift-Make-It-Compile-Challenge#2]
Challenge #3 uses a lazy method that is available in Xcode 7 beta6 and not in beta 5.

**Comment by Kametrixom** [comment]
@kostiakoval Are you using beta 5 right now? Can you tell me if `lazy([1, 2, 3])` compiles?

**Comment by kostiakoval** [comment]
yes in beta 5 `lazy([1, 2, 3])` compiles 
in beta 6 no. In beta 6 its '[1, 2, 3].lazy'

**Comment by Kametrixom** [comment]
Okay, I made a comment on this part of the code, Thanks :D
